[default]
src = 'src'
out = 'out'
solc = '0.8.10'

libs = ['lib']
remappings = [
    'ds-test/=lib/ds-test/src/',
    'solmate/=lib/solmate/src/',
    'weiroll/=lib/weiroll/src/'
]

# See more config options https://github.com/gakonst/foundry/tree/master/config
